### ISSUE TITLE
Can't view the website locally (server noob alert!)

### ISSUE THREAD

**Issue by GizKockesen** [alex9311/Information-Retrieval#41]
I copied the new folder for the template with the php files etc. to my desktop to start editing. however, when I open them in my browser, the css files aren't working and I only see the text with links. I know they normally work and I'm missing something server-related :S I'm just a big noob when it comes to the server-side of things so I have no clue what I need to do to view and edit these php pages :(

**Comment by alex9311** [comment]
Hey, its probably my fault, were you able to do that before?

**Comment by GizKockesen** [comment]
I could view the html files but I can't view the php files. I might be
doing something silly and missing something important though :S

**Comment by alex9311** [comment]
I just pushed a change (moving the library folder back into the project) want to try again? I'm hoping that fixes it

**Comment by GizKockesen** [comment]
Now I see the html pages but still not the php ones, so they're the ones
without the header that you created. Might be a stupid question, but do I
need to connect to the server to view the php files? Sorry for my noob
level!

**Comment by HDking** [comment]
php need a host to run. HTML files can run your browser

**Comment by alex9311** [comment]
Ah yeah thats probably your issue, i didn't think of that when moving the common stuff into php.

hmmm. Is this going to be a problem?

**Comment by HDking** [comment]
You can recreate a html file without the PHP links in them and play around with it. This is what I do for the voting page.

**Comment by GizKockesen** [comment]
Ohhhhhh okay. So when I add my php form, I add it to the html page. Okay
cool thanks guys!
